name: Bug Report
description: File a bug report
labels: [bug]
body:
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: "What operating system are you using ?"
      options:
        - Windows
        - MacOS
        - Linux
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: "What browser are you using ?"
      options:
        - Google Chrome
        - Microsoft Edge
        - Vivaldi
        - Brave
        - Opera
    validations:
      required: true
  - type: input
    id: browser_version
    attributes:
      label: Browser Version
      description: "Please enter your browser version"
      placeholder: "e.g. 91.0.4472.164"
    validations:
      required: false
  - type: textarea
    id: Description
    attributes:
      label: Describe the bug
      description: "A clear and concise description of the bug"
      render: bash
    validations:
      required: true
  - type: textarea
    id: RepoSteps
    attributes:
      label: Repo Steps
      description: "Steps to reproduce the behavior"
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
        ...
      render: bash
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      render: bash
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
